import type { Metadata } from 'next';
import { Inter } from 'next/font/google'; // Using Inter as base font
import './globals.css';
import { Navbar, Footer } from './component';
import { Scroller } from '@/lib/ui';
import ChatBot from './component/bot';
import SplashCursor from '@/lib/ui/splashcursor';

// Define your base font (Inter in this case)
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-base',
  adjustFontFallback: false, // Disable default fallback
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-system`}>
        <Navbar />
        <Scroller />
        {children}
        <ChatBot />
        <Footer />
        <SplashCursor />
      </body>
    </html>
  );
}